Feature/get by id performance
Gulfaam/HRCMS-Back-End-V1 pull request #14
Opened 2023-03-31 10:29 UTC by Azmat7860

Sir Please review the code of get Performance by ID API.

2023-03-31 10:52 UTC, Azmat7860 commented
Sir please review the code now i think it's fine.

2023-04-03 07:29 UTC, AbubakarZorrain requested changes

2023-04-03 07:29 UTC, AbubakarZorrain commented on models/performance.js
> +  // { timestamps: true },
Remove these comments...

2023-04-03 07:29 UTC, AbubakarZorrain commented on routes/index.js
Remove empty lines from import.

2023-04-18 05:38 UTC, AbubakarZorrain commented
Resolve conflicts and comments.

2023-04-26 12:41 UTC, AbubakarZorrain approved these changes
Approved...

2023-04-26 12:42 UTC, merged