Create hierarchy
Gulfaam/HRCMS-Back-End-V1 pull request #30
Opened 2023-04-01 04:51 UTC by Sameerthe-Big-O

2023-04-01 04:53 UTC, Sameerthe-Big-O commented
i'll add the code of each functionality step by step so that's why i've removed the whole previous code

2023-04-03 08:04 UTC, AbubakarZorrain requested changes

2023-04-03 08:04 UTC, AbubakarZorrain commented on routes/employee/controller.js
> +        const addResponse = await EmployeeServices.adsd(req.body, req.file.path);
What is adsd? Rename it correctly.

2023-04-03 08:04 UTC, AbubakarZorrain commented on services/hierarchy.js
> +export default hierarchySerive;
What is hierarchySerive, rename it correctly.

2023-04-03 08:04 UTC, AbubakarZorrain commented on validations/hierarchy.validation.js
> +export default validations
Rename it as per file name.

2023-04-03 10:40 UTC, Sameerthe-Big-O commented on config/env.js
> +  mongodbUri: process.env.DB_URI || "mongodb://127.0.0.1:27017/HRMS",
sir i just tried using MongoDB live but i was having some error and time is runing so just for now i'll be working with local if you approve

2023-04-03 10:48 UTC, closed without merging