Update the hierarchy
Gulfaam/HRCMS-Back-End-V1 pull request #33
Opened 2023-04-01 09:13 UTC by Sameerthe-Big-O

2023-04-03 08:16 UTC, Sameerthe-Big-O commented
Aoa sir just i'll be adding the if else conditions for status code

2023-04-03 08:42 UTC, AbubakarZorrain requested changes

2023-04-03 08:42 UTC, AbubakarZorrain commented on config/env.js
> +  mongodbUri: process.env.DB_URI || "mongodb://127.0.0.1:27017/HRMS",
Use Live db.

2023-04-03 08:42 UTC, AbubakarZorrain commented on dsd
> +  create-hierarchy[m
What is this file?

2023-04-03 08:42 UTC, AbubakarZorrain commented on routes/Hierarchy/controllers.js
> +      return httpResponse.SUCCESS(res, addResponse);
Status Code?

2023-04-03 08:42 UTC, AbubakarZorrain commented on services/hierarchy.js
> +        return { message: "success", data };
Do not send message from service layer. just send data. handle message in controller.

2023-04-03 08:42 UTC, AbubakarZorrain commented on services/hierarchy.js
>  export default hierarchySerive;
Rename it correctly...

2023-04-04 10:11 UTC, Sameerthe-Big-O reviewed
please review

2023-04-04 11:15 UTC, AbubakarZorrain requested changes
Resolve Conflicts

2023-04-05 04:45 UTC, AbubakarZorrain requested changes
Resolve Conflicts...

2023-04-07 04:53 UTC, closed without merging