Delete the hierarchy
Gulfaam/HRCMS-Back-End-V1 pull request #34
Opened 2023-04-01 09:14 UTC by Sameerthe-Big-O

2023-04-03 08:11 UTC, Sameerthe-Big-O commented
just noticed i haven't use if else conditions when the i'm getting the response back from the services

2023-04-03 08:44 UTC, AbubakarZorrain requested changes

2023-04-03 08:44 UTC, AbubakarZorrain commented on config/env.js
> +  mongodbUri: process.env.DB_URI || "mongodb://127.0.0.1:27017/HRMS",
Use Live MongoDb.

2023-04-03 08:44 UTC, AbubakarZorrain commented on config/env.js
> +  mongodbUri: process.env.DB_URI || "mongodb://127.0.0.1:27017/HRMS",
Why env  is in env.js?

2023-04-03 08:44 UTC, AbubakarZorrain commented on dsd
> +  create-hierarchy[m
What is this file doing

2023-04-03 08:44 UTC, AbubakarZorrain commented on services/hierarchy.js
> +        return { message: "success", data };
Do not send message from service layer. just send data. handle message in controller.

2023-04-03 08:44 UTC, AbubakarZorrain commented on services/hierarchy.js
> +        //*first checking if the hierarchy even exist on this id
Remove comments...

2023-04-04 10:09 UTC, Sameerthe-Big-O reviewed
review changes

2023-04-04 11:16 UTC, AbubakarZorrain requested changes
Resolve Conflicts

2023-04-05 04:44 UTC, AbubakarZorrain requested changes
Resolve Conflicts...

2023-04-07 04:53 UTC, closed without merging